# Generated by Django 4.2.29 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'prompt_item'), name='unique_user_prompt_purchase'),
        ),
    ]
