# Generated by Django 4.2.29 on 2026-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_purchase_unique_user_prompt_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_user_prompt_purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='promptitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
        ),
    ]
